### ISSUE TITLE
请问能否部署到自己的服务器

### ISSUE THREAD

**Issue by zbuhui** [Coande/pay2me#33]
如题，谢谢

**Comment by Coande** [comment]
可以的。可以自己从源码编译或者直接使用本仓库已编译好的（gh-pages 分支）。BTW，现在微信貌似已经不能从网页直接识别收款二维码了，需要保存二维码后再扫描付款。

**Comment by zbuhui** [comment]
> 

确实不能直接识别了,需要保存,没有办法了吗?

**Comment by Coande** [comment]
> > 
> 
> 确实不能直接识别了,需要保存,没有办法了吗?

没有办法
